version: '3'
services:
  bff:
    build: ./bff
    ports:
      - "3000:3000"
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3001:3000"
  mf_video:
    build: ./mf_video
    ports:
      - "3002:3000"
